### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by maasg** [gobuffalo/packr#51]
(GO noob here)
I'm trying to follow some instructions to build a `go` project. (I'm running Ubuntu 17.10 , go 1.10)
I set my `GOPATH` to a new `workspace` directory.  
Then, I installed `packr` using the instructions found in this project:
```
go get -u github.com/gobuffalo/packr/...
```
And when I try to run `packr` I get a segmentation fault:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6df339]

goroutine 633 [running]:
github.com/gobuffalo/packr/builder.(*visitor).eval(0xc4206cb810, 0x81a600, 0xc4204ea090, 0x0, 0x0)
  /.../gorkspace/src/github.com/gobuffalo/packr/builder/visitor.go:88 +0x69
github.com/gobuffalo/packr/builder.(*visitor).Visit(0xc4206cb810, 0x81a600, 0xc4204ea090, 0x818540, 0xc4206cb810)
  /.../gorkspace/src/github.com/gobuffalo/packr/builder/visitor.go:69 +0x4c
go/ast.Walk(0x818540, 0xc4206cb810, 0x81a600, 0xc4204ea090)
  /usr/local/go/src/go/ast/walk.go:52 +0x66
go/ast.walkDeclList(0x818540, 0xc4206cb810, 0xc420478600, 0xb, 0x10)
  /usr/local/go/src/go/ast/walk.go:38 +0x81
go/ast.Walk(0x818540, 0xc4206cb810, 0x81a580, 0xc420607200)
  /usr/local/go/src/go/ast/walk.go:353 +0x2650
github.com/gobuffalo/packr/builder.(*visitor).Run(0xc4206cb810, 0x9f86e8, 0x5a)
  /.../gorkspace/src/github.com/gobuffalo/packr/builder/visitor.go:42 +0x1e0
github.com/gobuffalo/packr/builder.(*Builder).process(0xc4200aa460, 0xc42040d0e0, 0x5a, 0xc420034448, 0xc4203eaf90)
  /.../gorkspace/src/github.com/gobuffalo/packr/builder/builder.go:90 +0x175
github.com/gobuffalo/packr/builder.(*Builder).Run.func1.1(0xc400000008, 0x7ed968)
  /.../gorkspace/src/github.com/gobuffalo/packr/builder/builder.go:48 +0x3c
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420034440, 0xc4204021c0)
  /.../gorkspace/src/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by golang.org/x/sync/errgroup.(*Group).Go
  /.../gorkspace/src/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

**Comment by markbates** [comment]
Can you provide some more steps, or even a small bit of a code, that can reproduce this?

**Comment by maasg** [comment]
The steps are as described in the bug submission:

1 install `packr` following the instructions in this repo: `go get -u github.com/gobuffalo/packr/...`
1 run: `$>packr`
`<core dump>`

There was no other code involved as I was following a step-by-step guide to setup a new project and struggled here.
I did continue the installation, and although running the command `packr` without any parameters results in the core dump, when I add a command, like `packr install` it works.

**Comment by markbates** [comment]
I can't reproduce, that's what I need some more information. Which guide were you running? What did the code you were running against look like? Unfortunately, if I can't reproduce, I can't fix it. :( If you can easily reproduce and want to take a crack at it, that would be great. Also information about your environment would be help, such as `go env`.

**Comment by maasg** [comment]
Thanks for looking into it. Let me try to reproduce it again with a fresh install. 
Here's my `go env`:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/<user>/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/<user>/gorkspace"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build303875554=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by markbates** [comment]
@maasg would you mind testing https://github.com/gobuffalo/packr/pull/52 since you can reproduce? I'm just taking a stab at it based on the file/line number of the error.

**Comment by maasg** [comment]
Sure. Do you have instructions on how to build from code? (Warning: go noob here)

**Comment by markbates** [comment]
Sure:

```
cd $GOPATH/src/github.com/gobuffalo/packr
git pull
git checkout -b fix-panic
go install -v ./...
```

That should do it.

**Comment by maasg** [comment]
Looks like the patch fixes the issue.

Here's the session transcript:
```
# First reproduce issue

gorkspace$ go get -u github.com/gobuffalo/packr/...
gorkspace$ packr
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6df339]

goroutine 635 [running]:
github.com/gobuffalo/packr/builder.(*visitor).eval(0xc420f00780, 0x81a600, 0xc420768d80, 0x0, 0x0)
  gorkspace/src/github.com/gobuffalo/packr/builder/visitor.go:88 +0x69
github.com/gobuffalo/packr/builder.(*visitor).Visit(0xc420f00780, 0x81a600, 0xc420768d80, 0x818540, 0xc420f00780)
  gorkspace/src/github.com/gobuffalo/packr/builder/visitor.go:69 +0x4c
go/ast.Walk(0x818540, 0xc420f00780, 0x81a600, 0xc420768d80)
  /usr/local/go/src/go/ast/walk.go:52 +0x66
go/ast.walkDeclList(0x818540, 0xc420f00780, 0xc420c3a100, 0xb, 0x10)
  /usr/local/go/src/go/ast/walk.go:38 +0x81
go/ast.Walk(0x818540, 0xc420f00780, 0x81a580, 0xc4202d2a80)
  /usr/local/go/src/go/ast/walk.go:353 +0x2650
github.com/gobuffalo/packr/builder.(*visitor).Run(0xc420f00780, 0x9f86e8, 0x5c)
  gorkspace/src/github.com/gobuffalo/packr/builder/visitor.go:42 +0x1e0
github.com/gobuffalo/packr/builder.(*Builder).process(0xc4200b6460, 0xc4207b1020, 0x5c, 0xc4200b83c8, 0xc4206af790)
  gorkspace/src/github.com/gobuffalo/packr/builder/builder.go:90 +0x175
github.com/gobuffalo/packr/builder.(*Builder).Run.func1.1(0xc400000008, 0x7ed968)
  gorkspace/src/github.com/gobuffalo/packr/builder/builder.go:48 +0x3c
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc4200b83c0, 0xc420efa4a0)
  gorkspace/src/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by golang.org/x/sync/errgroup.(*Group).Go
  gorkspace/src/golang.org/x/sync/errgroup/errgroup.go:55 +0x66

# Try patch

gorkspace$ cd $GOPATH/src/github.com/gobuffalo/packr
gorkspace/src/github.com/gobuffalo/packr$ git pull
Already up-to-date.
gorkspace/src/github.com/gobuffalo/packr$ git checkout fix-panic
Switched to branch 'fix-panic'
Your branch is up-to-date with 'origin/fix-panic'.
gorkspace/src/github.com/gobuffalo/packr$ go install -v ./...
gorkspace/src/github.com/gobuffalo/packr$ cd $GOPATH
gorkspace$ packr
gorkspace$ 

# Woot!
```

**Comment by markbates** [comment]
Woot! Thanks!

**Comment by maasg** [comment]
No, thank *you* for following it up so quickly!

**Comment by maasg** [comment]
Fixed with https://github.com/gobuffalo/packr/pull/52
